### ISSUE TITLE
Support for const (and/or single-value enums)

### ISSUE THREAD

**Issue by koscejev** [pwall567/json-kotlin-schema-codegen#11]
Thanks for sharing this project!

Would it be possible to support `const` or single-value `enum` as just pre-set value without constructor parameter?

Usecase: We're thinking about using this in our project, but we need to figure out how to support polymorphism in at least semi-intuitive way. I'm thinking the support of `const` would make the first step.

E.g., this jsonschema:
```yaml
title: Something Changed Event
allOf:
  - $ref: "Event.yaml"
  - $ref: "SomethingFields.yaml"
properties:
  type:
    const: "SomethingChangedEvent"
    default: "SomethingChangedEvent"
```

Along with this referenced `Event.yaml` parent:
```yaml
title: Event
type: object
required:
  - type
properties:
  type:
    type: string
```

Currently generate this child:
```kotlin
class SomethingChangedEvent(
    type: String = "SomethingChangedEvent",
    val other: Other
) : Event(type)
```

But this would be more error-proof if `const` would result in this child being generated:
```kotlin
class SomethingChangedEvent(
    val other: Other
) : Event(type = "SomethingChangedEvent")
```

Regarding the usecase, one possible next step for us would be to use Jackson2 mixins to also (manually) add polymorphic deserialization support based on this.

I'm not sure how this should work without polymorphism involved, though - perhaps `type` in this case could be just `val` field that is not present in constructor parameters? Is this reasonable?

**Comment by pwall567** [comment]
Hi - thanks for these suggestions.  On the first point, using the `const` value as a parameter to the base constructor from the derived class - I like the idea, but I took the approach of creating a field (and a constructor parameter) for each property.  Your suggestion would mean that the constructor for the derived class would not have a parameter for the constant value.

As you pointed out in your later comment, when you use `const` in a simple case with no inheritance it adds an `init` check on the value.  That is what I had planned - the property is present, but the `const` forces a check which means that the constructor will fail if the wrong value is used.  The fact that it doesn't output the check when the class is a derived class is a bug, and I am looking into it now.

I don't like your idea of re-ordering the fields - I think most people would expect constructor parameters to be in the same order as in the schema.  Using Kotlin named parameters it's easy to include just the parameters you need.

On your second point, support for polymorphism - this is tricky because it depends on the serialization / deserialization library being used.  I made an early design decision that the generated code should not contain any dependencies on other libraries, and I like to think that the code can be used by any of the JSON libraries.

Here I must declare a bias - I have my own serialization / deserialization library named [kjson](https://github.com/pwall567/kjson), and while I know that other libraries have a strong presence (you mentioned Jackson in one of your comments), I think that mine has real advantages.  It is native Kotlin, rather than a Kotlin facade on Java, it supports Kotlin classes like `Pair` and `Triple`, and it includes non-blocking output, for use in a coroutine environment.

It includes polymorphic deserialization - see the section on [fromJSONPolymorphic](https://github.com/pwall567/kjson/blob/main/CUSTOM.md#fromjsonpolymorphic).  In my day job, I use this functionality to deserialize CloudEvents, using the `type` field in the CloudEvents envelope to determine which target class to use.

Of course, none of this is automated.  I think it would be difficult to generate classes that could be deserialized automatically in a polymorphic manner, and any inclusion of library-dependent code would violate the principle I mentioned earlier of not adding dependencies on other libraries.  But I'm interested to know how others are tackling the problem, and if a more automated means of deserializing members of a class hierarchy can be found, that could be a valuable addition to the library.

**Comment by koscejev** [comment]
Thanks for a very informative reply!

Regarding kjson library, I think we could take a look into using it, but ultimately one of the reasons we're using Jackson is that it's "tried and true", so we have a lot of experience with using it, how to handle which problems, how it integrates with Spring Framework, what performance we can expect from it, etc. So switching is currently somewhat unlikely.

How would you recommend defining jsonschema for support of polymorphism? The way I was trying to do it with "type" property and "const" values in children?

**Comment by koscejev** [comment]
Regarding changing order of properties. I found a somewhat interesting workaround. If I only mark "type" property as required in parent, but don't actually define it, then I can define it as the last property in each child and it works surprisingly well. Perhaps we could be satisfied with this approach for another reason: if the parent doesn't have any properties at all, then children are generated as native `data class`, which is arguably even better. I just don't know if this will be supported by Jackson or any other deserialization framework.

**Comment by pwall567** [comment]
In regard to the question of the recommended way of defining classes that are to be deserialized polymorphically - yes, I support the idea of defining a a "type" field in the base schema and redefining the same field as `const` with a specific value for each sub-schema.  How you make use of that in your deserialization library will be specific that that library, and it's difficult to see how it could be automated.  I am considering adding a configuration option to allow annotations to be added to classes or fields, but that is probably some way in the future.

Generating code for a `oneOf` presents some difficult challenges.  As you have found, if there are no shared fields, the generator can create classes using the name from the `$ref`, but when the class needs to combine properties from outside the `oneOf` with those inside, it has to generate a new name ("A", "B" etc.).  I am considering adding to the configuration option which currently allows you to choose an output class name (see [`classNames`](https://github.com/pwall567/json-kotlin-schema-codegen/blob/main/CONFIG.md#classnames)), extending it to allow control over the choice of nested class names as well.  That would require some manual configuration on your part, but it would be much simpler to implement than any automated mechanism for deriving the names.

**Comment by pwall567** [comment]
Keep it open - I have worked out a fix for that missing validation bug, and I should be able to get a new version uploaded to Maven Central within 24 hours.  I'll notify you here.

Regarding `oneOf` - if the parent schema contains no properties of its own, just the `oneOf` with members consisting only of a single `$ref`, it will output the parent as an `interface` and use the name derived from the `$ref` for the child classes.  That can be useful, but it doesn't guarantee that a type discriminator property exists in the base, which is what I think you're trying to achieve.

I think we're both hitting against the mismatch between the JSON Schema specification and the requirements of polymorphism.  In any case, this has been a useful discussion, and I hope you're able to make productive use of the library.

**Comment by koscejev** [comment]
I couldn't make it generate `interface`, but after your comment I tried a bit more thoroughly and it turns out it's not enough that there are no fields, I also need to remove `type: object` for it to generate `interface`. But although it generated `interface`, it wasn't used in child classes at all, when those classes have `allOf` in them. It works if I use just one `$ref` in the child directly (and there's no parent class), but no longer works once I wrap it in `allOf` (and a parent class is generated). Is this a bug? Also it's a bit strange that direct `$ref` actually uses the fields from the `$ref`, but doesn't use it as a parent.

Parent:
```yaml
$schema: https://json-schema.org/draft-07/schema
title: Event
description: Generic parent for all events
oneOf:
  - $ref: SomethingChangedEvent.yaml
  - $ref: SomethingUpdatedEvent.yaml
```

Child (has parent, doesn't implement interface):
```yaml
$schema: https://json-schema.org/draft-07/schema
title: Something Changed Event
description: Event when Something changed
allOf:
  - $ref: "Something.yaml"
properties:
  type:
    type: string
    const: SomethingChangedEvent
    default: SomethingChangedEvent
```

Child (no parent, implements interface):
```yaml
$schema: https://json-schema.org/draft-07/schema
title: Something Changed Event
description: Event when Something changed
$ref: "Something.yaml"
properties:
  type:
    type: string
    const: SomethingChangedEvent
    default: SomethingChangedEvent
```
