### ISSUE TITLE
Generate `typealias Object = Any` when type cannot be determined

### ISSUE THREAD

**Issue by cmpaul** [pwall567/json-kotlin-schema-codegen#28]
Hi @pwall567 👋 

We are generating a schema that allows for an `Untyped` type that will allow any valid JSON type:

```yaml
$defs:
  MyType:
    type: object
    properties:
      data:
        "$ref": "#/$defs/Untyped"
  Untyped:
    type:
    - array
    - boolean
    - integer
    - number
    - object
    - string
```

There is no error, but this simply fails to generate a data class for `Untyped`, and therefore the resulting Kotlin code does not compile. 

In cases like this where a single type cannot be determined, one option is to generate a class with a `typealias`:

```kotlin
// Untyped.kt
typealias Untyped = Any
```

I have drafted a PR to demonstrate what we are looking for here: #27 

What do you think?
